config/routes.rb
Ativa::Application.routes.draw do
  root to: "projects#index"
  get 'projects/:id/:phase/:show_partial' => 'projects#show', as: 'project_partial'
  get 'projects/:id/:phase' => 'projects#set_phase', as: 'set_phase'
  resources :projects
  resources :posts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/phase.rb
class Phase < ActiveRecord::Base
  attr_accessible :name

  has_many :posts
  has_many :projects

  def progress_level
  	levels = {
  		"onboarding" => 9,
  		"creative" => 29,
  		"design" => 50,
  		"development" => 71,
  		"implementation" => 91
  	}
  	return levels[self.name]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :attachment, :message, :title, :phase_id, :project_id
  belongs_to :project
  belongs_to :phase

  default_scope order('created_at DESC')

  mount_uploader :attachment, ImageUploader

  def snippet
    message_size = 90 + rand(150)
    snippet = self.message.truncate(message_size, :separator => ' ')
    return snippet
  end
  
  def attachment_image(size)
  	if self.attachment?
  		return self.attachment_url(size)
  	else
  		random_images = [
			"http://www.dbcovers.com/imagenes/backdrops/grandes/happy_gilmore_1996//happy_gilmore_1996_1.jpg",
			"http://www.themusclecarplace.com/wp-content/uploads/2012/11/happy-gilmore.jpg",
			"http://3.bp.blogspot.com/-FBbhGnSrbRQ/TtwGcsrKiFI/AAAAAAAAAFY/XpIAJj65sFo/s1600/Happy-Gilmore-01-4.jpg",
			"http://chicago.bridgesinternational.com/assets/images/uploads/galleries/uic/chicago-poetry-calendar.jpg",
			"http://www.richard-seaman.com/USA/Cities/Chicago/Landmarks/ChicagoAtNight1.jpg",
			"http://images.wikia.com/fanfiction/images/4/4e/Youre_gonna_die_clown_-_Happy_Gilmore.jpg",
			"http://upload.wikimedia.org/wikipedia/commons/f/f4/Chicago_Bears_vs_Tennessee_Titans_11-09-08.jpg"
		]
  		random_image = random_images[self.id % 7]
  		return random_image
  	end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	attr_accessible :name, :phase_id
	has_many :posts
	belongs_to :phase

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  has_secure_password
  before_save :downcase_email
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
include SessionsHelper

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.phase_id = Phase.find_by_name(params[:post][:phase_id]).id

    respond_to do |format|
      if @post.save
        format.html { redirect_to project_partial_path(@post.project.id, @post.phase.name, 'posts'), notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to project_partial_path(@post.project.id, @post.phase.name, 'post', post_id: @post.id), notice: 'Post was successfully updated.' }
      else
        format.html { redirect_to project_partial_path(@post.project.id, @post.phase.name, 'post', post_id: @post.id), notice: "Umm, we weren't able to update this post" }
      end
    end

  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @phases = Phase.all

    @show_partial = params[:show_partial]
    
    if @show_partial == 'posts'
      @posts = @project.posts.where(phase_id: Phase.find_by_name(params[:phase]).id).order
    elsif @show_partial == 'post'
      @post = Post.find(params[:post_id])
    elsif @show_partial == 'new_post'
      @post = Post.new
    elsif @show_partial == 'edit_post'
      @post = Post.find(params[:post_id])
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def set_phase
    project = Project.find(params[:id])
    project.phase_id = Phase.find_by_name(params[:phase]).id
    project.save

    redirect_to project_partial_url(project.id, project.phase.name, 'posts')
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end


	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:remember_token] = user.id
			redirect_to user

		else
			flash[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def new
	 @user = User.new
  end

  def show
	  @user = User.find(params[:id])
  end

  def create
	  @user = User.new(params[:user])
    if @user.save
		  flash[:success] = "Welcome to my awesome app!"
		  redirect_to @user
	  else
		  render 'new'
	  end
  end

  def index
	 @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def progress_bar(phase)
  	levels = {
  		"onboarding" => 9,
  		"creative" => 29,
  		"design" => 50,
  		"development" => 71,
  		"implementation" => 91
  	}
  	return levels[phase]
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed_in?
    if session[:remember_token] && user.id
      true
    else
      false
    end
  end 

  def current_user
    if user.signed_in?
      User.find_by_id(user.id)
    else
      nil
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Ativa | Perfect Search Design</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag('logo.png', :width => '180px'), root_url, :class => "brand" %>
      <%= if user.signed_in? %>
        <div class="nav-collapse pull-right">
            <ul class="nav">       
              <li><%= link_to "All Users", users_path %></li>
              <li><%= link_to "My Profile", user_path %></li>
              <li><%= link_to "Sign Out", signout_path %></li>
            </ul>
          </div>
      <%= else %>

          <div class="nav-collapse pull-right">
            <ul class="nav">       
              <li><%= link_to "All Users", users_path %></li>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Sign In", signin_path %></li>
            </ul>
          </div>
        <%= end %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.haml
.row_fluid
  .span1
  .span10
    %h2
      Active Projects
      %small= link_to "Add Project", new_project_url

.row-fluid
  .span2
  .span8
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %th.span6 Project Name
          %th.span6 Last Updated
      %tbody
        - @projects.each do |project|
          %tr
            %td
              = link_to project.name, project_partial_url(project.id, project.phase.name, 'posts')
            %td= project.updated_at.strftime("%m/%d/%y at %I:%M%P")
  .span2

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.haml
.sideNavcontent
	.row-fluid
		.span12
			.row-fluid
				.span1
				.page-header.pagination-centered.span10
					%h1= link_to @project.name, project_partial_path(@project.id, @project.phase.name, "posts")
					.btn-group
						%button.btn.dropdown-toggle{"data-toggle" => "dropdown"}
							Phase
							%span.caret
						%ul.dropdown-menu
							- @phases.each do |phase|
								%li= link_to phase.name, set_phase_url(@project.id, phase.name)
				.span1
			/ Progress Bar
			.row-fluid
				.span1
				.progress.progress-striped.success.span10
					.bar{:style => "width: #{progress_bar(@project.phase.name)}%;"}
				.span1
			/ The five phases
			.row-fluid
				.span1
				- @phases.each do |phase|
					.span2.pagination-centered.phase
						%div{:class => "#{if params[:phase] == phase.name then 'active' end}"}
							= link_to phase.name, project_partial_url(@project.id, phase.name, 'posts')
				.span1
			.row-fluid
				.span1
				.span10
					%h2
						= params[:phase].capitalize + " Phase"
						%small= link_to 'add post', project_partial_path(@project.id, params[:phase], 'new_post')
				.span1
			= if @show_partial then render "projects/show_partials/#{@show_partial}" else render "projects/show_partials/posts"  end

app/views/projects/show_partials/_edit_post.html.haml
.row-fluid
  .span2
  .span8
    .row-fluid
      = form_for @post, :html => {multipart: true} do |f|
        .field
          = f.text_field :title, placeholder: "Title"
        .field
          = f.text_area :message, rows: 4, style: 'width: 100%;'
        .field
          = f.file_field :attachment, style: 'width: 60%;'

          = f.hidden_field :project_id, value: @project.id
          = f.hidden_field :phase_id, value: @post.phase.id

        .actions
          = f.submit 'Update'
  .span1

app/views/projects/show_partials/_new_post.html.haml
.row-fluid
  .span2
  .span8
    .row-fluid
      = form_for @post, :html => {multipart: true} do |f|
        .field
          = f.text_field :title, placeholder: "Title"
        .field
          = f.text_area :message, rows: 4, style: 'width: 100%;', placeholder: "Type your message..."
        .field
          = f.file_field :attachment, style: 'width: 60%;', placeholder: "Paste a URL for your attachment"

          = f.hidden_field :project_id, value: @project.id
          = f.hidden_field :phase_id, value: params[:phase]

        .actions
          = f.submit 'Upload'
  .span1

app/views/projects/show_partials/_post.html.haml
.row-fluid
	.span1
	.span10
		.active
			%h4
				= @post.title
				%small= @post.updated_at.strftime("%m/%d/%y at %I:%M%P")
				%small= link_to 'edit', project_partial_url(@project.id, params[:phase], 'edit_post', post_id: @post.id)
			%p
	.span1
.row_fluid
	.span1
	.span11
		%p= @post.message
		= image_tag @post.attachment_image(:medium), height: "1000", width:"100%"

app/views/projects/show_partials/_posts.html.haml
- @posts.each do |post|
	.row-fluid
		.span1
		.span1
			%ul.media-list
				%li.media
					%a.pull-left{:href => "user_url(post.user)"}
						= image_tag "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash3/c163.36.546.546/s160x160/14986_10151378874079699_689397579_n.jpg", :class => "media-object img-rounded pagination-centered", :width => "60"
						%p.pagination-centered Shaan
		.media-body
			.span8
				%h4.media-heading
					= link_to post.title, project_partial_url(@project.id, params[:phase], 'post', post_id: post.id)
					%small= post.updated_at.strftime("%m/%d/%y at %I:%M%P")
				%p= post.snippet
			.span2
				= image_tag post.attachment_image(:thumb)

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Check out my friends</h1>
<% @users.each do |u| %>
	<h3><%= link_to u.name, u %></h3>
	<p>Email at <%= u.email %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up for my awesome app!</h1>
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <br />
  
  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <br />
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <br />
  
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <br />
  
  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
  <%= gravatar_for @user %>
</h1>
<p>
  <%= @user.email %>
</p>